name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          INSTAPAPER_CONSUMER_KEY: consumer_key
          INSTAPAPER_CONSUMER_SECRET: consumer_secret
